import { 
  BrazilData, 
  SpainData, 
  SouthKoreaData, 
  AmericanData, 
  Country 
} from './types';

export const brazilData: BrazilData[] = [
  {
    number: '415',
    name: 'Gabriel Santos',
    phone: '+34 698123456',
    profession: 'Engenheiro de Software',
    weight: 78,
    height: 180,
    status: 'PAGO',
  },
  {
    number: '3243',
    name: 'Felipe Rocha',
    phone: '+34 634123987',
    profession: 'Analista de Marketing',
    weight: 76,
    height: 178,
    status: 'PAGO',
  },
  {
    number: '3344',
    name: 'Jéssica Alves',
    phone: '+34 698543210',
    profession: 'Engenheira de Software',
    weight: 65,
    height: 165,
    status: 'AGUARDANDO',
  },
  {
    number: '3445',
    name: 'Ricardo Costa',
    phone: '+34 612987654',
    profession: 'Médico',
    weight: 83,
    height: 182,
    status: 'CANCELADO',
  },
  {
    number: '3546',
    name: 'Sabrina Oliveira',
    phone: '+34 698765432',
    profession: 'Estilista',
    weight: 58,
    height: 160,
    status: 'ATRASADO',
  },
  {
    number: '3647',
    name: 'Guilherme Santos',
    phone: '+34 634567890',
    profession: 'Programador',
    weight: 79,
    height: 180,
    status: 'PAGO',
  },
  {
    number: '3748',
    name: 'Daniele Lima',
    phone: '+34 612345789',
    profession: 'Fotógrafa',
    weight: 62,
    height: 168,
    status: 'AGUARDANDO',
  },
  {
    number: '3849',
    name: 'Diego Martins',
    phone: '+34 698765431',
    profession: 'Gerente de Vendas',
    weight: 88,
    height: 183,
    status: 'CANCELADO',
  },
  {
    number: '3950',
    name: 'Patrícia Mendes',
    phone: '+34 634123456',
    profession: 'Psicóloga',
    weight: 56,
    height: 162,
    status: 'ATRASADO',
  },
  {
    number: '4051',
    name: 'Marcio Almeida',
    phone: '+34 612345678',
    profession: 'Ator',
    weight: 81,
    height: 181,
    status: 'PAGO',
  },
  {
    number: '4152',
    name: 'Tatiane Oliveira',
    phone: '+34 698543210',
    profession: 'Recepcionista',
    weight: 59,
    height: 164,
    status: 'AGUARDANDO',
  },
  {
    number: '4253',
    name: 'Leandro Silva',
    phone: '+34 634567890',
    profession: 'Desenvolvedor Mobile',
    weight: 74,
    height: 175,
    status: 'CANCELADO',
  },
  {
    number: '4354',
    name: 'Luana Costa',
    phone: '+34 612987654',
    profession: 'Gerente de Recursos Humanos',
    weight: 65,
    height: 170,
    status: 'ATRASADO',
  },
  {
    number: '4455',
    name: 'Rafael Souza',
    phone: '+34 698765432',
    profession: 'Engenheiro Mecânico',
    weight: 82,
    height: 180,
    status: 'PAGO',
  },
  {
    number: '4556',
    name: 'Karine Martins',
    phone: '+34 634123456',
    profession: 'Tradutora',
    weight: 53,
    height: 158,
    status: 'AGUARDANDO',
  },
  {
    number: '4657',
    name: 'Mariana Lima',
    phone: '+34 612345678',
    profession: 'Bióloga',
    weight: 67,
    height: 166,
    status: 'CANCELADO',
  },
  {
    number: '4758',
    name: 'Vinicius Almeida',
    phone: '+34 698543210',
    profession: 'Assistente Administrativo',
    weight: 75,
    height: 179,
    status: 'ATRASADO',
  },
  {
    number: '4859',
    name: 'Aline Ferreira',
    phone: '+34 634567890',
    profession: 'Mestre de Cerimônias',
    weight: 60,
    height: 165,
    status: 'PAGO',
  },
  {
    number: '4960',
    name: 'Eduardo Lima',
    phone: '+34 612987654',
    profession: 'Técnico de Enfermagem',
    weight: 78,
    height: 180,
    status: 'AGUARDANDO',
  },
  {
    number: '5061',
    name: 'Sérgio Santos',
    phone: '+34 698765431',
    profession: 'Arquiteto',
    weight: 85,
    height: 183,
    status: 'CANCELADO',
  },
  {
    number: '5162',
    name: 'Roberta Oliveira',
    phone: '+34 634123456',
    profession: 'Consultora de Imagem',
    weight: 66,
    height: 171,
    status: 'ATRASADO',
  },
  {
    number: '5263',
    name: 'Gustavo Martins',
    phone: '+34 612345789',
    profession: 'Designer de Produtos',
    weight: 70,
    height: 176,
    status: 'PAGO',
  },
  {
    number: '5364',
    name: 'Tatiane Ribeiro',
    phone: '+34 698543210',
    profession: 'Gerente de Projetos',
    weight: 62,
    height: 164,
    status: 'AGUARDANDO',
  },
  {
    number: '5465',
    name: 'Fernando Almeida',
    phone: '+34 634567890',
    profession: 'Veterinário',
    weight: 79,
    height: 182,
    status: 'CANCELADO',
  },
  {
    number: '5566',
    name: 'Jessica Costa',
    phone: '+34 612987654',
    profession: 'Contadora',
    weight: 55,
    height: 160,
    status: 'ATRASADO',
  },
  {
    number: '5667',
    name: 'Matheus Silva',
    phone: '+34 698765432',
    profession: 'Empresário',
    weight: 91,
    height: 186,
    status: 'PAGO',
  },
  {
    number: '5768',
    name: 'Camila Pereira',
    phone: '+34 634123456',
    profession: 'Assistente de Marketing',
    weight: 58,
    height: 165,
    status: 'AGUARDANDO',
  },
  {
    number: '5869',
    name: 'Lucas Rodrigues',
    phone: '+34 612345678',
    profession: 'Gerente de Vendas',
    weight: 77,
    height: 179,
    status: 'CANCELADO',
  },
  {
    number: '5970',
    name: 'Sofia Lima',
    phone: '+34 698543210',
    profession: 'Estudante',
    weight: 60,
    height: 167,
    status: 'ATRASADO',
  },
  {
    number: '516',
    name: 'Sofia Lima',
    phone: '+34 612345780',
    profession: 'Dentista',
    weight: 62,
    height: 165,
    status: 'AGUARDANDO',
  },
  {
    number: '617',
    name: 'Fernando Ribeiro',
    phone: '+34 698765431',
    profession: 'Arquiteto',
    weight: 72,
    height: 173,
    status: 'CANCELADO',
  },
  {
    number: '718',
    name: 'Juliana Martins',
    phone: '+34 634123789',
    profession: 'Desenvolvedora Web',
    weight: 55,
    height: 160,
    status: 'ATRASADO',
  },
  {
    number: '819',
    name: 'Lucas Almeida',
    phone: '+34 612987123',
    profession: 'Fotógrafo',
    weight: 70,
    height: 178,
    status: 'PAGO',
  },
  {
    number: '920',
    name: 'Mariana Oliveira',
    phone: '+34 698543789',
    profession: 'Psicóloga',
    weight: 63,
    height: 162,
    status: 'AGUARDANDO',
  },
  {
    number: '1021',
    name: 'Roberto Souza',
    phone: '+34 634567890',
    profession: 'Professor',
    weight: 85,
    height: 185,
    status: 'CANCELADO',
  },
  {
    number: '1122',
    name: 'Ana Beatriz',
    phone: '+34 612345690',
    profession: 'Médica',
    weight: 58,
    height: 170,
    status: 'ATRASADO',
  },
  {
    number: '1223',
    name: 'Thiago Ferreira',
    phone: '+34 698765430',
    profession: 'Chef',
    weight: 80,
    height: 177,
    status: 'PAGO',
  },
  {
    number: '1324',
    name: 'Camila Costa',
    phone: '+34 634123456',
    profession: 'Arquiteta',
    weight: 65,
    height: 169,
    status: 'AGUARDANDO',
  },
  {
    number: '1425',
    name: 'Eduardo Lima',
    phone: '+34 612345654',
    profession: 'Engenheiro Civil',
    weight: 90,
    height: 182,
    status: 'CANCELADO',
  },
  {
    number: '1526',
    name: 'Fernanda Rocha',
    phone: '+34 698543210',
    profession: 'Designer Gráfico',
    weight: 54,
    height: 161,
    status: 'ATRASADO',
  },
  {
    number: '1627',
    name: 'Rafael Gomes',
    phone: '+34 634567890',
    profession: 'Músico',
    weight: 75,
    height: 176,
    status: 'PAGO',
  },
  {
    number: '1728',
    name: 'Clara Martins',
    phone: '+34 612345678',
    profession: 'Jornalista',
    weight: 60,
    height: 164,
    status: 'AGUARDANDO',
  },
  {
    number: '1829',
    name: 'Vinícius Almeida',
    phone: '+34 698765431',
    profession: 'Analista de Sistemas',
    weight: 77,
    height: 179,
    status: 'CANCELADO',
  },
  {
    number: '1930',
    name: 'Isabela Oliveira',
    phone: '+34 634123456',
    profession: 'Programadora',
    weight: 64,
    height: 167,
    status: 'ATRASADO',
  },
  {
    number: '2031',
    name: 'Felipe Souza',
    phone: '+34 612987654',
    profession: 'Desenvolvedor Frontend',
    weight: 74,
    height: 180,
    status: 'PAGO',
  },
  {
    number: '2132',
    name: 'Bianca Costa',
    phone: '+34 698543210',
    profession: 'Recepcionista',
    weight: 55,
    height: 159,
    status: 'AGUARDANDO',
  },
  {
    number: '2233',
    name: 'André Lima',
    phone: '+34 634567890',
    profession: 'Estudante',
    weight: 70,
    height: 175,
    status: 'CANCELADO',
  },
  {
    number: '2334',
    name: 'Patrícia Silva',
    phone: '+34 612345789',
    profession: 'Bióloga',
    weight: 62,
    height: 165,
    status: 'ATRASADO',
  },
  {
    number: '2435',
    name: 'Júlio Santos',
    phone: '+34 698765432',
    profession: 'Motorista',
    weight: 85,
    height: 178,
    status: 'PAGO',
  },
  {
    number: '2536',
    name: 'Aline Ferreira',
    phone: '+34 634123456',
    profession: 'Fisioterapeuta',
    weight: 58,
    height: 161,
    status: 'AGUARDANDO',
  },
  {
    number: '2637',
    name: 'Robson Costa',
    phone: '+34 612345678',
    profession: 'Veterinário',
    weight: 72,
    height: 170,
    status: 'CANCELADO',
  },
  {
    number: '2738',
    name: 'Gustavo Lima',
    phone: '+34 698543210',
    profession: 'Arquiteto',
    weight: 80,
    height: 182,
    status: 'ATRASADO',
  },
  {
    number: '2839',
    name: 'Tatiane Almeida',
    phone: '+34 634567890',
    profession: 'Engenheira Ambiental',
    weight: 63,
    height: 167,
    status: 'PAGO',
  },
  {
    number: '2940',
    name: 'Marcos Paulo',
    phone: '+34 612987654',
    profession: 'Ator',
    weight: 75,
    height: 179,
    status: 'AGUARDANDO',
  },
  {
    number: '3041',
    name: 'Debora Santos',
    phone: '+34 698765431',
    profession: 'Designer de Interiores',
    weight: 65,
    height: 172,
    status: 'CANCELADO',
  },
  {
    number: '3142',
    name: 'Lucas Almeida',
    phone: '+34 612345780',
    profession: 'Gerente de Projetos',
    weight: 85,
    height: 183,
    status: 'ATRASADO',
  },
  {
    number: '1025',
    name: 'Roberto Santos',
    phone: '+34 612345025',
    profession: 'Arquiteto',
    weight: 74,
    height: 170,
    status: 'PAGO',
  },
  {
    number: '1026',
    name: 'Gabriela Almeida',
    phone: '+34 612345026',
    profession: 'Programadora',
    weight: 68,
    height: 165,
    status: 'AGUARDANDO',
  },
  {
    number: '1027',
    name: 'Rafael Ribeiro',
    phone: '+34 612345027',
    profession: 'Jornalista',
    weight: 82,
    height: 177,
    status: 'CANCELADO',
  },
  {
    number: '1028',
    name: 'Thais Martins',
    phone: '+34 612345028',
    profession: 'Chef',
    weight: 60,
    height: 160,
    status: 'ATRASADO',
  },
  {
    number: '1029',
    name: 'Felipe Nascimento',
    phone: '+34 612345029',
    profession: 'Psicólogo',
    weight: 78,
    height: 180,
    status: 'PAGO',
  },
  {
    number: '1030',
    name: 'Ana Clara',
    phone: '+34 612345030',
    profession: 'Vendedora',
    weight: 62,
    height: 162,
    status: 'AGUARDANDO',
  },
  {
    number: '1031',
    name: 'Lucas Oliveira',
    phone: '+34 612345031',
    profession: 'Engenheiro',
    weight: 75,
    height: 173,
    status: 'CANCELADO',
  },
  {
    number: '1032',
    name: 'Vanessa Costa',
    phone: '+34 612345032',
    profession: 'Professora',
    weight: 54,
    height: 159,
    status: 'ATRASADO',
  },
  {
    number: '1033',
    name: 'Diego Gomes',
    phone: '+34 612345033',
    profession: 'Designer',
    weight: 79,
    height: 178,
    status: 'PAGO',
  },
  {
    number: '1034',
    name: 'Marina Ferreira',
    phone: '+34 612345034',
    profession: 'Médica',
    weight: 66,
    height: 165,
    status: 'AGUARDANDO',
  },
  {
    number: '1035',
    name: 'Carlos Eduardo',
    phone: '+34 612345035',
    profession: 'Engenheiro',
    weight: 82,
    height: 176,
    status: 'CANCELADO',
  },
  {
    number: '1050',
    name: 'Fernanda Lima',
    phone: '+34 612345050',
    profession: 'Engenheira de Alimentos',
    weight: 68,
    height: 165,
    status: 'AGUARDANDO',
  },
  {
    number: '1051',
    name: 'Gustavo Mendes',
    phone: '+34 612345051',
    profession: 'Arquiteto',
    weight: 77,
    height: 180,
    status: 'CANCELADO',
  },
  {
    number: '1052',
    name: 'Juliana Santos',
    phone: '+34 612345052',
    profession: 'Professora de Matemática',
    weight: 63,
    height: 159,
    status: 'PAGO',
  },
  {
    number: '1053',
    name: 'André Costa',
    phone: '+34 612345053',
    profession: 'Programador Front-end',
    weight: 75,
    height: 174,
    status: 'AGUARDANDO',
  },
  {
    number: '1054',
    name: 'Tatiane Souza',
    phone: '+34 612345054',
    profession: 'Designer de Interiores',
    weight: 60,
    height: 157,
    status: 'CANCELADO',
  },
  {
    number: '1055',
    name: 'Rafael Almeida',
    phone: '+34 612345055',
    profession: 'Engenheiro Mecânico',
    weight: 85,
    height: 182,
    status: 'ATRASADO',
  },
  {
    number: '1056',
    name: 'Mariana Oliveira',
    phone: '+34 612345056',
    profession: 'Psicóloga Clínica',
    weight: 58,
    height: 160,
    status: 'PAGO',
  },
  {
    number: '1057',
    name: 'Leonardo Nascimento',
    phone: '+34 612345057',
    profession: 'Veterinário',
    weight: 76,
    height: 177,
    status: 'AGUARDANDO',
  },
  {
    number: '1058',
    name: 'Isabella Ferreira',
    phone: '+34 612345058',
    profession: 'Chef de Pâtisserie',
    weight: 55,
    height: 155,
    status: 'CANCELADO',
  },
  {
    number: '1059',
    name: 'Bruno Martins',
    phone: '+34 612345059',
    profession: 'Designer de Moda',
    weight: 72,
    height: 173,
    status: 'ATRASADO',
  },
  {
    number: '1060',
    name: 'Patricia Alves',
    phone: '+34 612345060',
    profession: 'Professora de História',
    weight: 64,
    height: 165,
    status: 'PAGO',
  },
  {
    number: '1061',
    name: 'Thiago Pereira',
    phone: '+34 612345061',
    profession: 'Engenheiro Civil',
    weight: 78,
    height: 178,
    status: 'AGUARDANDO',
  },
  {
    number: '1062',
    name: 'Aline Costa',
    phone: '+34 612345062',
    profession: 'Médica Veterinária',
    weight: 70,
    height: 172,
    status: 'CANCELADO',
  },
  {
    number: '1063',
    name: 'Caio Santos',
    phone: '+34 612345063',
    profession: 'Programador de Jogos',
    weight: 83,
    height: 180,
    status: 'ATRASADO',
  },
  {
    number: '1064',
    name: 'Clara Lima',
    phone: '+34 612345064',
    profession: 'Arquiteta Paisagista',
    weight: 62,
    height: 160,
    status: 'PAGO',
  },
  {
    number: '1065',
    name: 'Felipe Gomes',
    phone: '+34 612345065',
    profession: 'Pesquisador',
    weight: 75,
    height: 175,
    status: 'AGUARDANDO',
  },
  {
    number: '1066',
    name: 'Juliana Rocha',
    phone: '+34 612345066',
    profession: 'Consultora de Beleza',
    weight: 58,
    height: 158,
    status: 'CANCELADO',
  },
  {
    number: '1067',
    name: 'Eduardo Ferreira',
    phone: '+34 612345067',
    profession: 'Artista Gráfico',
    weight: 80,
    height: 183,
    status: 'ATRASADO',
  },
  {
    number: '1068',
    name: 'Marcelino Teixeira',
    phone: '+34 612345068',
    profession: 'Pediatra',
    weight: 70,
    height: 165,
    status: 'PAGO',
  },
  {
    number: '1069',
    name: 'Sabrina Pires',
    phone: '+34 612345069',
    profession: 'Engenheira de Software',
    weight: 63,
    height: 160,
    status: 'AGUARDANDO',
  },
  {
    number: '1070',
    name: 'Felipe Oliveira',
    phone: '+34 612345070',
    profession: 'Analista de Sistemas',
    weight: 82,
    height: 178,
    status: 'CANCELADO',
  },
  {
    number: '1071',
    name: 'Vanessa Martins',
    phone: '+34 612345071',
    profession: 'Médica',
    weight: 65,
    height: 162,
    status: 'ATRASADO',
  },
  {
    number: '1072',
    name: 'Roberto Sousa',
    phone: '+34 612345072',
    profession: 'Cientista de Dados',
    weight: 90,
    height: 182,
    status: 'PAGO',
  },
  {
    number: '1073',
    name: 'Patrícia Alves',
    phone: '+34 612345073',
    profession: 'Técnica de Enfermagem',
    weight: 60,
    height: 159,
    status: 'AGUARDANDO',
  },
  {
    number: '1074',
    name: 'Lucas Martins',
    phone: '+34 612345074',
    profession: 'Químico',
    weight: 78,
    height: 175,
    status: 'CANCELADO',
  },
  {
    number: '1075',
    name: 'Natalia Figueiredo',
    phone: '+34 612345075',
    profession: 'Economista',
    weight: 65,
    height: 170,
    status: 'ATRASADO',
  },
  {
    number: '1076',
    name: 'Thiago Almeida',
    phone: '+34 612345076',
    profession: 'Fisioterapeuta',
    weight: 70,
    height: 180,
    status: 'PAGO',
  },
  {
    number: '1077',
    name: 'Fernanda Cruz',
    phone: '+34 612345077',
    profession: 'Publicitária',
    weight: 57,
    height: 158,
    status: 'AGUARDANDO',
  },
  {
    number: '1078',
    name: 'João Carlos',
    phone: '+34 612345078',
    profession: 'Cozinheiro',
    weight: 75,
    height: 177,
    status: 'CANCELADO',
  },
  {
    number: '1079',
    name: 'Cintia Rios',
    phone: '+34 612345079',
    profession: 'Bióloga',
    weight: 62,
    height: 165,
    status: 'ATRASADO',
  },
  {
    number: '1080',
    name: 'Ricardo Dias',
    phone: '+34 612345080',
    profession: 'Historiador',
    weight: 80,
    height: 182,
    status: 'PAGO',
  },
  {
    number: '1081',
    name: 'Gabriela Silva',
    phone: '+34 612345081',
    profession: 'Jornalista',
    weight: 55,
    height: 155,
    status: 'AGUARDANDO',
  },
  {
    number: '1082',
    name: 'Marcelo Torres',
    phone: '+34 612345082',
    profession: 'Engenheiro Civil',
    weight: 88,
    height: 185,
    status: 'CANCELADO',
  },
  {
    number: '1083',
    name: 'Isabella Nascimento',
    phone: '+34 612345083',
    profession: 'Assistente Social',
    weight: 66,
    height: 160,
    status: 'ATRASADO',
  },
  {
    number: '1084',
    name: 'Sérgio Martins',
    phone: '+34 612345084',
    profession: 'Gerente de Projetos',
    weight: 75,
    height: 177,
    status: 'PAGO',
  },
  {
    number: '1085',
    name: 'Alessandra Souza',
    phone: '+34 612345085',
    profession: 'Engenheira Ambiental',
    weight: 68,
    height: 170,
    status: 'AGUARDANDO',
  },
  {
    number: '1086',
    name: 'Danilo Ferreira',
    phone: '+34 612345086',
    profession: 'Veterinário',
    weight: 72,
    height: 178,
    status: 'PAGO',
  },
  {
    number: '1087',
    name: 'Tatiane Lima',
    phone: '+34 612345087',
    profession: 'Designer Gráfico',
    weight: 58,
    height: 162,
    status: 'AGUARDANDO',
  },
  {
    number: '1088',
    name: 'Carlos Eduardo',
    phone: '+34 612345088',
    profession: 'Contador',
    weight: 85,
    height: 180,
    status: 'CANCELADO',
  },
  {
    number: '1089',
    name: 'Bruna Ferreira',
    phone: '+34 612345089',
    profession: 'Farmacêutica',
    weight: 63,
    height: 164,
    status: 'ATRASADO',
  },
  {
    number: '1090',
    name: 'Leandro Gomes',
    phone: '+34 612345090',
    profession: 'Engenheiro Eletricista',
    weight: 78,
    height: 182,
    status: 'PAGO',
  },
  {
    number: '1091',
    name: 'Patrícia Lopes',
    phone: '+34 612345091',
    profession: 'Assistente Administrativa',
    weight: 59,
    height: 155,
    status: 'AGUARDANDO',
  },
  {
    number: '1092',
    name: 'Mário Henrique',
    phone: '+34 612345092',
    profession: 'Analista de Marketing',
    weight: 76,
    height: 176,
    status: 'CANCELADO',
  },
  {
    number: '1093',
    name: 'Juliana Souza',
    phone: '+34 612345093',
    profession: 'Engenheira Química',
    weight: 66,
    height: 167,
    status: 'ATRASADO',
  },
  {
    number: '1094',
    name: 'Rodrigo Santos',
    phone: '+34 612345094',
    profession: 'Desenvolvedor Front-end',
    weight: 80,
    height: 185,
    status: 'PAGO',
  },
  {
    number: '1095',
    name: 'Tatiane Rodrigues',
    phone: '+34 612345095',
    profession: 'Arquiteta Paisagista',
    weight: 61,
    height: 161,
    status: 'AGUARDANDO',
  },
  {
    number: '1096',
    name: 'Fernando Martins',
    phone: '+34 612345096',
    profession: 'Professor Universitário',
    weight: 74,
    height: 179,
    status: 'CANCELADO',
  },
  {
    number: '1097',
    name: 'Simone Oliveira',
    phone: '+34 612345097',
    profession: 'Artista Plástico',
    weight: 54,
    height: 158,
    status: 'ATRASADO',
  },
  {
    number: '1098',
    name: 'Fábio Ribeiro',
    phone: '+34 612345098',
    profession: 'Pintor',
    weight: 77,
    height: 180,
    status: 'PAGO',
  },
  {
    number: '1099',
    name: 'Viviane Costa',
    phone: '+34 612345099',
    profession: 'Tradutora',
    weight: 60,
    height: 163,
    status: 'AGUARDANDO',
  },
  {
    number: '1100',
    name: 'Gilberto Alves',
    phone: '+34 612345100',
    profession: 'Fisioterapeuta',
    weight: 79,
    height: 173,
    status: 'CANCELADO',
  },
  {
    number: '1101',
    name: 'Eliane Pereira',
    phone: '+34 612345101',
    profession: 'Nutricionista',
    weight: 58,
    height: 160,
    status: 'ATRASADO',
  },
  {
    number: '1102',
    name: 'Cristiano Ribeiro',
    phone: '+34 612345102',
    profession: 'Engenheiro de Produção',
    weight: 85,
    height: 190,
    status: 'PAGO',
  },
  {
    number: '1103',
    name: 'Amanda Rodrigues',
    phone: '+34 612345103',
    profession: 'Psicóloga',
    weight: 62,
    height: 162,
    status: 'AGUARDANDO',
  },
  {
    number: '1104',
    name: 'Rafael Oliveira',
    phone: '+34 612345104',
    profession: 'Músico',
    weight: 70,
    height: 175,
    status: 'CANCELADO',
  },
  {
    number: '1105',
    name: 'Isabel Cristina',
    phone: '+34 612345105',
    profession: 'Assistente de Vendas',
    weight: 65,
    height: 168,
    status: 'ATRASADO',
  },
  {
    number: '1036',
    name: 'Patrícia Souza',
    phone: '+34 612345036',
    profession: 'Arquiteta',
    weight: 69,
    height: 162,
    status: 'ATRASADO',
  },
  {
    number: '1037',
    name: 'Jorge Almeida',
    phone: '+34 612345037',
    profession: 'Professor',
    weight: 75,
    height: 174,
    status: 'PAGO',
  },
  {
    number: '1038',
    name: 'Claudia Nunes',
    phone: '+34 612345038',
    profession: 'Designer Gráfico',
    weight: 60,
    height: 158,
    status: 'AGUARDANDO',
  },
  {
    number: '1039',
    name: 'Fernando Lima',
    phone: '+34 612345039',
    profession: 'Médico',
    weight: 80,
    height: 180,
    status: 'CANCELADO',
  },
  {
    number: '1040',
    name: 'Bianca Martins',
    phone: '+34 612345040',
    profession: 'Psicóloga',
    weight: 65,
    height: 165,
    status: 'ATRASADO',
  },
  {
    number: '1041',
    name: 'Ricardo Dias',
    phone: '+34 612345041',
    profession: 'Programador',
    weight: 78,
    height: 179,
    status: 'PAGO',
  },
  {
    number: '1042',
    name: 'Sofia Oliveira',
    phone: '+34 612345042',
    profession: 'Arquiteta',
    weight: 70,
    height: 172,
    status: 'AGUARDANDO',
  },
  {
    number: '1043',
    name: 'Vinícius Silva',
    phone: '+34 612345043',
    profession: 'Engenheiro de Software',
    weight: 85,
    height: 182,
    status: 'CANCELADO',
  },
  {
    number: '1044',
    name: 'Elaine Costa',
    phone: '+34 612345044',
    profession: 'Professora',
    weight: 62,
    height: 160,
    status: 'ATRASADO',
  },
  {
    number: '1045',
    name: 'Daniel Rocha',
    phone: '+34 612345045',
    profession: 'Designer',
    weight: 72,
    height: 177,
    status: 'PAGO',
  },
  {
    number: '1046',
    name: 'Tatiane Martins',
    phone: '+34 612345046',
    profession: 'Vendedora',
    weight: 57,
    height: 155,
    status: 'AGUARDANDO',
  },
  {
    number: '1047',
    name: 'Luiz Fernando',
    phone: '+34 612345047',
    profession: 'Engenheiro Civil',
    weight: 90,
    height: 185,
    status: 'CANCELADO',
  },
  {
    number: '1048',
    name: 'Amanda Lima',
    phone: '+34 612345048',
    profession: 'Jornalista',
    weight: 65,
    height: 163,
    status: 'ATRASADO',
  },
  {
    number: '1049',
    name: 'Pedro Henrique',
    phone: '+34 612345049',
    profession: 'Chef de Cozinha',
    weight: 80,
    height: 178,
    status: 'PAGO',
  },
  {
    number: '135',
    name: 'Lucas Silva',
    phone: '+34 612345678',
    profession: 'Engenheiro',
    weight: 70,
    height: 175,
    status: 'PAGO',
  },
  {
    number: '190',
    name: 'Ana Costa',
    phone: '+34 698765432',
    profession: 'Professora',
    weight: 60,
    height: 160,
    status: 'AGUARDANDO',
  },
  {
    number: '205',
    name: 'Pedro Gomes',
    phone: '+34 634567890',
    profession: 'Designer',
    weight: 75,
    height: 180,
    status: 'CANCELADO',
  },
  {
    number: '278',
    name: 'Maria Oliveira',
    phone: '+34 612987654',
    profession: 'Médica',
    weight: 65,
    height: 165,
    status: 'ATRASADO',
  },
  {
    number: '314',
    name: 'Fernanda Pereira',
    phone: '+34 698543210',
    profession: 'Arquiteta',
    weight: 68,
    height: 170,
    status: 'PAGO',
  },
  {
    number: '431',
    name: 'Carlos Santos',
    phone: '+34 634123456',
    profession: 'Programador',
    weight: 80,
    height: 182,
    status: 'AGUARDANDO',
  },
  {
    number: '512',
    name: 'Patrícia Almeida',
    phone: '+34 612345789',
    profession: 'Jornalista',
    weight: 55,
    height: 158,
    status: 'CANCELADO',
  },
  {
    number: '628',
    name: 'Rafael Mendes',
    phone: '+34 698765321',
    profession: 'Chef',
    weight: 82,
    height: 177,
    status: 'ATRASADO',
  },
  {
    number: '753',
    name: 'Juliana Ferreira',
    phone: '+34 634567123',
    profession: 'Psicóloga',
    weight: 64,
    height: 162,
    status: 'PAGO',
  },
  {
    number: '864',
    name: 'Tiago Martins',
    phone: '+34 612789456',
    profession: 'Vendedor',
    weight: 70,
    height: 172,
    status: 'AGUARDANDO',
  },

];

export const spainData: SpainData[] = [
  {
    number: '1',
    shirtNumber: '7',
    name: 'Fernando Torres',
    nationality: 'Espanhol',
    team: 'Atlético de Madrid',
  },
  {
    number: '2',
    shirtNumber: '10',
    name: 'Lionel Messi',
    nationality: 'Argentino',
    team: 'Barcelona',
  },
  {
    number: '3',
    shirtNumber: '11',
    name: 'Neymar Jr.',
    nationality: 'Brasileiro',
    team: 'Paris Saint-Germain',
  },
  {
    number: '4',
    shirtNumber: '4',
    name: 'Sergio Ramos',
    nationality: 'Espanhol',
    team: 'Real Madrid',
  },
  {
    number: '5',
    shirtNumber: '8',
    name: 'Andrés Iniesta',
    nationality: 'Espanhol',
    team: 'Barcelona',
  },
  {
    number: '6',
    shirtNumber: '9',
    name: 'David Villa',
    nationality: 'Espanhol',
    team: 'Valência',
  },
  {
    number: '7',
    shirtNumber: '21',
    name: 'Cesc Fàbregas',
    nationality: 'Espanhol',
    team: 'Chelsea',
  },
  {
    number: '8',
    shirtNumber: '16',
    name: 'Javi Martínez',
    nationality: 'Espanhol',
    team: 'Bayern de Munique',
  },
  {
    number: '9',
    shirtNumber: '3',
    name: 'Gerard Piqué',
    nationality: 'Espanhol',
    team: 'Barcelona',
  },
  {
    number: '10',
    shirtNumber: '6',
    name: 'Xavi Hernández',
    nationality: 'Espanhol',
    team: 'Barcelona',
  },

];

export const southKoreaData: SouthKoreaData[] = [
  {
    number: '13',
    name: 'ENHYPEN',
    memberCount: 7,
    debutYear: 2020,
    genre: 'K-Pop',
    label: 'BELIFT LAB',
    hitSong: 'Drunk-Dazed',
  },
  {
    number: '14',
    name: '(G)I-DLE',
    memberCount: 6,
    debutYear: 2018,
    genre: 'K-Pop',
    label: 'CUBE 엔터테인먼트',
    hitSong: 'TOMBOY',
  },
  {
    number: '15',
    name: 'Treasure',
    memberCount: 12,
    debutYear: 2020,
    genre: 'K-Pop',
    label: 'YG 엔터테인먼트',
    hitSong: 'Going Crazy',
  },
  {
    number: '16',
    name: 'SF9',
    memberCount: 9,
    debutYear: 2016,
    genre: 'K-Pop',
    label: 'FNC 엔터테인먼트',
    hitSong: 'Good Guy',
  },
  {
    number: '17',
    name: 'BTOB',
    memberCount: 7,
    debutYear: 2012,
    genre: 'K-Pop',
    label: 'CUBE 엔터테인먼트',
    hitSong: 'Missing You',
  },
  {
    number: '18',
    name: 'VICTON',
    memberCount: 7,
    debutYear: 2016,
    genre: 'K-Pop',
    label: 'Play M Entertainment',
    hitSong: 'What I Said',
  },
  {
    number: '19',
    name: 'ATEEZ',
    memberCount: 8,
    debutYear: 2018,
    genre: 'K-Pop',
    label: 'KQ 엔터테인먼트',
    hitSong: 'Say My Name',
  },
  {
    number: '20',
    name: 'NCT 127',
    memberCount: 10,
    debutYear: 2016,
    genre: 'K-Pop',
    label: 'SM 엔터테인먼트',
    hitSong: 'Kick It',
  },
  {
    number: '21',
    name: 'GFRIEND',
    memberCount: 6,
    debutYear: 2015,
    genre: 'K-Pop',
    label: 'Source Music',
    hitSong: 'Rough',
  },
  {
    number: '22',
    name: 'CLC',
    memberCount: 7,
    debutYear: 2015,
    genre: 'K-Pop',
    label: 'CUBE 엔터테인먼트',
    hitSong: 'No',
  },
  {
    number: '23',
    name: 'Lovelyz',
    memberCount: 8,
    debutYear: 2014,
    genre: 'K-Pop',
    label: 'Woollim Entertainment',
    hitSong: 'Destiny',
  },
  {
    number: '24',
    name: 'WJSN',
    memberCount: 12,
    debutYear: 2016,
    genre: 'K-Pop',
    label: 'Starship Entertainment',
    hitSong: 'Secret',
  },
  {
    number: '25',
    name: 'I.O.I',
    memberCount: 11,
    debutYear: 2016,
    genre: 'K-Pop',
    label: 'YMC Entertainment',
    hitSong: 'Pick Me',
  },
  {
    number: '26',
    name: 'Pristin',
    memberCount: 10,
    debutYear: 2017,
    genre: 'K-Pop',
    label: 'Pledis Entertainment',
    hitSong: 'Wee Woo',
  },
  {
    number: '27',
    name: 'Cherry Bullet',
    memberCount: 10,
    debutYear: 2019,
    genre: 'K-Pop',
    label: 'FNC Entertainment',
    hitSong: 'Q&A',
  },
  {
    number: '28',
    name: 'Rocket Punch',
    memberCount: 6,
    debutYear: 2019,
    genre: 'K-Pop',
    label: 'Woollim Entertainment',
    hitSong: 'Bouncy',
  },
  {
    number: '31',
    name: '2NE1',
    memberCount: 4,
    debutYear: 2009,
    genre: 'K-Pop',
    label: 'YG 엔터테인먼트',
    hitSong: 'I Am The Best',
  },
  {
    number: '32',
    name: 'Big Bang',
    memberCount: 5,
    debutYear: 2006,
    genre: 'K-Pop',
    label: 'YG 엔터테인먼트',
    hitSong: 'Fantastic Baby',
  },
  {
    number: '33',
    name: 'SHINee',
    memberCount: 5,
    debutYear: 2008,
    genre: 'K-Pop',
    label: 'SM 엔터테인먼트',
    hitSong: 'Ring Ding Dong',
  },
  {
    number: '34',
    name: 'Super Junior',
    memberCount: 13,
    debutYear: 2005,
    genre: 'K-Pop',
    label: 'SM 엔터테인먼트',
    hitSong: 'Sorry, Sorry',
  },
  {
    number: '35',
    name: 'Girls\' Generation',
    memberCount: 9,
    debutYear: 2007,
    genre: 'K-Pop',
    label: 'SM 엔터테인먼트',
    hitSong: 'Gee',
  },
  {
    number: '36',
    name: 'f(x)',
    memberCount: 5,
    debutYear: 2009,
    genre: 'K-Pop',
    label: 'SM 엔터테인먼트',
    hitSong: 'Electric Shock',
  },
  {
    number: '37',
    name: 'SISTAR',
    memberCount: 4,
    debutYear: 2010,
    genre: 'K-Pop',
    label: 'Starship Entertainment',
    hitSong: 'Touch My Body',
  },
  {
    number: '38',
    name: 'EXID',
    memberCount: 5,
    debutYear: 2012,
    genre: 'K-Pop',
    label: 'LE Entertainment',
    hitSong: 'Up & Down',
  },
  {
    number: '39',
    name: 'MOMOLAND',
    memberCount: 9,
    debutYear: 2016,
    genre: 'K-Pop',
    label: 'Mnet Entertainment',
    hitSong: 'Bboom Bboom',
  },
  {
    number: '40',
    name: 'Apink',
    memberCount: 6,
    debutYear: 2011,
    genre: 'K-Pop',
    label: 'Plan A Entertainment',
    hitSong: 'NoNoNo',
  },
  {
    number: '41',
    name: 'Brown Eyed Girls',
    memberCount: 4,
    debutYear: 2006,
    genre: 'K-Pop',
    label: 'Nega Network',
    hitSong: 'Abracadabra',
  },
  {
    number: '42',
    name: 'Wonder Girls',
    memberCount: 5,
    debutYear: 2007,
    genre: 'K-Pop',
    label: 'JYP Entertainment',
    hitSong: 'Nobody',
  },
  {
    number: '43',
    name: 'Girl\'s Day',
    memberCount: 4,
    debutYear: 2010,
    genre: 'K-Pop',
    label: 'Dream Tea Entertainment',
    hitSong: 'Something',
  },
  {
    number: '44',
    name: 'ZICO',
    memberCount: 1,
    debutYear: 2012,
    genre: 'K-Pop',
    label: 'KOZ Entertainment',
    hitSong: 'Any Song',
  },
  {
    number: '45',
    name: 'HIGHLIGHT',
    memberCount: 5,
    debutYear: 2009,
    genre: 'K-Pop',
    label: 'Around Us Entertainment',
    hitSong: 'Plz Don’t Be Sad',
  },
  {
    number: '46',
    name: 'WINNER',
    memberCount: 4,
    debutYear: 2014,
    genre: 'K-Pop',
    label: 'YG Entertainment',
    hitSong: 'Really Really',
  },
  {
    number: '47',
    name: 'iKON',
    memberCount: 7,
    debutYear: 2015,
    genre: 'K-Pop',
    label: 'YG Entertainment',
    hitSong: 'Love Scenario',
  },
  {
    number: '48',
    name: 'A-JAX',
    memberCount: 5,
    debutYear: 2012,
    genre: 'K-Pop',
    label: 'DSP Media',
    hitSong: 'One 4 U',
  },
  {
    number: '49',
    name: 'B.A.P',
    memberCount: 6,
    debutYear: 2012,
    genre: 'K-Pop',
    label: 'TS Entertainment',
    hitSong: 'Warrior',
  },
  {
    number: '50',
    name: 'TEEN TOP',
    memberCount: 6,
    debutYear: 2010,
    genre: 'K-Pop',
    label: 'TOP Media',
    hitSong: 'Crazy',
  },
  {
    number: '29',
    name: 'Gugudan',
    memberCount: 8,
    debutYear: 2016,
    genre: 'K-Pop',
    label: 'Jellyfish Entertainment',
    hitSong: 'Not That Type',
  },
  {
    number: '30',
    name: 'Momoland',
    memberCount: 9,
    debutYear: 2016,
    genre: 'K-Pop',
    label: 'Mnet Entertainment',
    hitSong: 'Bboom Bboom',
  },
  {
    number: '1',
    name: 'BTS',
    memberCount: 7,
    debutYear: 2013,
    genre: 'K-Pop',
    label: '빅히트 엔터테인먼트',
    hitSong: 'Dynamite',
  },
  {
    number: '2',
    name: 'BLACKPINK',
    memberCount: 4,
    debutYear: 2016,
    genre: 'K-Pop',
    label: 'YG 엔터테인먼트',
    hitSong: '뚜두뚜두 (DDU-DU DDU-DU)',
  },
  {
    number: '3',
    name: 'EXO',
    memberCount: 9,
    debutYear: 2012,
    genre: 'K-Pop',
    label: 'SM 엔터테인먼트',
    hitSong: 'Love Shot',
  },
  {
    number: '4',
    name: 'TWICE',
    memberCount: 9,
    debutYear: 2015,
    genre: 'K-Pop',
    label: 'JYP 엔터테인먼트',
    hitSong: 'Fancy',
  },
  {
    number: '5',
    name: 'GOT7',
    memberCount: 7,
    debutYear: 2014,
    genre: 'K-Pop',
    label: 'JYP 엔터테인먼트',
    hitSong: 'Just Right',
  },
  {
    number: '6',
    name: 'Red Velvet',
    memberCount: 5,
    debutYear: 2014,
    genre: 'K-Pop',
    label: 'SM 엔터테인먼트',
    hitSong: 'Psycho',
  },
  {
    number: '7',
    name: 'SEVENTEEN',
    memberCount: 13,
    debutYear: 2015,
    genre: 'K-Pop',
    label: '플레디스 엔터테인먼트',
    hitSong: 'Left & Right',
  },
  {
    number: '8',
    name: 'ITZY',
    memberCount: 5,
    debutYear: 2019,
    genre: 'K-Pop',
    label: 'JYP 엔터테인먼트',
    hitSong: 'Wannabe',
  },
  {
    number: '9',
    name: 'MAMAMOO',
    memberCount: 4,
    debutYear: 2014,
    genre: 'K-Pop',
    label: 'RBW',
    hitSong: 'HIP',
  },
  {
    number: '10',
    name: 'Stray Kids',
    memberCount: 8,
    debutYear: 2018,
    genre: 'K-Pop',
    label: 'JYP 엔터테인먼트',
    hitSong: 'God’s Menu',
  },
  {
    number: '11',
    name: 'ATEEZ',
    memberCount: 8,
    debutYear: 2018,
    genre: 'K-Pop',
    label: 'KQ 엔터테인먼트',
    hitSong: 'Inception',
  },
  {
    number: '12',
    name: 'TXT',
    memberCount: 5,
    debutYear: 2019,
    genre: 'K-Pop',
    label: '빅히트 엔터테인먼트',
    hitSong: 'Crown',
  },
];

export const americanData: AmericanData[] = [
  {
    number: '1',
    party: "Democratic",
    name: "Joe Biden",
    stateOfOrigin: "Delaware",
    positionHeld: "President of the United States",
    yearAssumedOffice: 2021,
    age: 81,
    politicalIdeology: "Moderate liberal policies, focus on unity and infrastructure."
  },
  {
    number: '2',
    party: "Republican",
    name: "Donald Trump",
    stateOfOrigin: "New York",
    positionHeld: "Former President of the United States",
    yearAssumedOffice: 2017,
    age: 77,
    politicalIdeology: "Populist policies, America First agenda."
  },
  {
    number: '3',
    party: "Conservative",
    name: "Rishi Sunak",
    stateOfOrigin: "Yorkshire",
    positionHeld: "Prime Minister of the United Kingdom",
    yearAssumedOffice: 2022,
    age: 43,
    politicalIdeology: "Centre-right policies, fiscal responsibility."
  },
  {
    number: '4',
    party: "Republican",
    name: "Ron DeSantis",
    stateOfOrigin: "Florida",
    positionHeld: "Governor of Florida",
    yearAssumedOffice: 2019,
    age: 45,
    politicalIdeology: "Conservative policies, focus on education and business."
  },
  {
    number: '5',
    party: "Democratic",
    name: "Kamala Harris",
    stateOfOrigin: "California",
    positionHeld: "Vice President of the United States",
    yearAssumedOffice: 2021,
    age: 59,
    politicalIdeology: "Progressive policies, advocate for social justice."
  },
  {
    number: '6',
    party: "Independent",
    name: "Bernie Sanders",
    stateOfOrigin: "Vermont",
    positionHeld: "U.S. Senator from Vermont",
    yearAssumedOffice: 2007,
    age: 83,
    politicalIdeology: "Democratic socialism, universal healthcare, income inequality."
  },
  {
    number: '7',
    party: "Liberal",
    name: "Justin Trudeau",
    stateOfOrigin: "Quebec",
    positionHeld: "Prime Minister of Canada",
    yearAssumedOffice: 2015,
    age: 52,
    politicalIdeology: "Progressive policies, focus on diversity and environmental issues."
  },
  {
    number: '8',
    party: "Democratic",
    name: "Gavin Newsom",
    stateOfOrigin: "California",
    positionHeld: "Governor of California",
    yearAssumedOffice: 2019,
    age: 56,
    politicalIdeology: "Progressive policies, healthcare and climate change focus."
  },
  {
    number: '9',
    party: "Socialist",
    name: "Alexandria Ocasio-Cortez",
    stateOfOrigin: "New York",
    positionHeld: "U.S. Representative from New York",
    yearAssumedOffice: 2019,
    age: 34,
    politicalIdeology: "Democratic socialism, green new deal advocacy."
  },
  {
    number: '10',
    party: "Democratic",
    name: "Stacey Abrams",
    stateOfOrigin: "Georgia",
    positionHeld: "Politician and Activist",
    yearAssumedOffice: "N/A",
    age: 50,
    politicalIdeology: "Voting rights advocacy, progressive policies."
  },
  {
    number: '11',
    party: "Republican",
    name: "Nikki Haley",
    stateOfOrigin: "South Carolina",
    positionHeld: "Former U.S. Ambassador to the United Nations",
    yearAssumedOffice: 2017,
    age: 52,
    politicalIdeology: "Conservative policies, focus on foreign relations."
  },
  {
    number: '12',
    party: "Democratic",
    name: "Andrew Cuomo",
    stateOfOrigin: "New York",
    positionHeld: "Former Governor of New York",
    yearAssumedOffice: 2011,
    age: 66,
    politicalIdeology: "Progressive policies, focus on public health."
  },
  {
    number: '13',
    party: "Liberal",
    name: "Jacinda Ardern",
    stateOfOrigin: "New Zealand",
    positionHeld: "Former Prime Minister of New Zealand",
    yearAssumedOffice: 2017,
    age: 44,
    politicalIdeology: "Progressive policies, focus on mental health and climate change."
  },
  {
    number: '14',
    party: "Social Democratic",
    name: "Olaf Scholz",
    stateOfOrigin: "Germany",
    positionHeld: "Chancellor of Germany",
    yearAssumedOffice: 2021,
    age: 65,
    politicalIdeology: "Social democracy, focus on economic stability and social justice."
  }
];

export const countriesTab: Country[] = [
  { label: 'Brazil', value: 'BR', lengthData: brazilData.length },
  { label: 'United States', value: 'US', lengthData: americanData.length  },
  { label: 'South Korea', value: 'KR', lengthData: southKoreaData.length },
  { label: 'Spain', value: 'ES', lengthData: spainData.length },
];

export const textCountriesTab = {
  'BR': 'A tabela contém informações sobre cidadãos brasileiros, incluindo nome, profissão, peso, altura e status de pagamento. Esses dados ajudam a entender o perfil demográfico e profissional da população.',
  'ES': 'La tabla incluye datos sobre jugadores de fútbol españoles, destacando su número de camiseta, nombre, nacionalidad y equipo. Estos datos son útiles para analizar la trayectoria y el rendimiento de los jugadores en sus respectivos clubes.',
  'KR': '이 표에는 K-Pop 그룹의 정보가 포함되어 있으며, 그룹 이름, 멤버 수, 데뷔 연도, 장르 및 히트 송이 나열되어 있습니다. 이 데이터는 K-Pop의 인기와 그룹의 영향력을 이해하는 데 도움을 줍니다.',
  'US': 'The table provides information about American political figures, including their party affiliation, name, state of origin, position held, and political ideology. This data helps to analyze the political landscape and the diversity of leadership in the U.S.'
};
